// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThangDV29_MiniProject_WebAPI.ApplicationDBContext;

namespace ThangDV29_MiniProject_WebAPI.Migrations
{
    [DbContext(typeof(MyApplicationDBContext))]
    [Migration("20220614100015_updateSeedData")]
    partial class updateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Account", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAuthentication")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBLock")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            ID = new Guid("a68393ff-15fa-4136-85e2-71cdc505d8e8"),
                            BirthDay = new DateTime(1999, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreate = new DateTime(2022, 6, 14, 10, 0, 12, 0, DateTimeKind.Unspecified),
                            Email = "doanvanthang504@gmail.com",
                            FullName = "DOAN VAN THANG",
                            IsAuthentication = true,
                            IsBLock = false,
                            PasswordHash = "$2a$11$RpJwaoF5bJSC50bOgEE/peqDRf4TQ.RZeYCmE79z6Iaz5XvatFchq",
                            Role = 0,
                            Username = "doanvanthang504"
                        },
                        new
                        {
                            ID = new Guid("2c273e26-c2dd-4956-8e13-7c25c2a1158b"),
                            BirthDay = new DateTime(1998, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreate = new DateTime(2022, 6, 14, 10, 0, 13, 0, DateTimeKind.Unspecified),
                            Email = "lethihoa99@gmail.com",
                            FullName = "LE THI HOA",
                            IsAuthentication = true,
                            IsBLock = false,
                            PasswordHash = "$2a$11$I1YEMWSyYmlPXdgIIbPPQOBUbymIEy5VFQ.8k7yfkgSycdReiLTQm",
                            Role = 1,
                            Username = "lethihoa99"
                        },
                        new
                        {
                            ID = new Guid("23e22ae9-c14a-4e5d-8bf0-e4734143ed41"),
                            BirthDay = new DateTime(1988, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreate = new DateTime(2022, 6, 14, 10, 0, 13, 0, DateTimeKind.Unspecified),
                            Email = "taolagiaovien@gmail.com",
                            FullName = "tao la giao vien",
                            IsAuthentication = true,
                            IsBLock = false,
                            PasswordHash = "$2a$11$BypCuVlOrP/xpGygZGZ5AOkjZAaaalBcON2dIwvaBtPsetiW08bVG",
                            Role = 1,
                            Username = "giaovien"
                        },
                        new
                        {
                            ID = new Guid("e280d537-732c-465a-ab22-74d4cbb696c2"),
                            BirthDay = new DateTime(1988, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreate = new DateTime(2022, 6, 14, 10, 0, 13, 0, DateTimeKind.Unspecified),
                            Email = "taolagiaovien22@gmail.com",
                            FullName = "tao la giao vien 22",
                            IsAuthentication = true,
                            IsBLock = false,
                            PasswordHash = "$2a$11$2ZIvKnZEsbZAjo0Ime2lbepvKHD03Q71CpAiwM9O26184x2XxRRR.",
                            Role = 1,
                            Username = "giaovien2"
                        },
                        new
                        {
                            ID = new Guid("9c7b60b6-44b6-4a6f-9c4b-a0ece4672421"),
                            BirthDay = new DateTime(2000, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreate = new DateTime(2022, 6, 14, 10, 0, 13, 0, DateTimeKind.Unspecified),
                            Email = "nguyenvananh123@gmail.com",
                            FullName = "NGUYEN VAN ANH",
                            IsAuthentication = false,
                            IsBLock = false,
                            PasswordHash = "$2a$11$5tBeQ7.N/H3XHsrpBnUuZ.WQCHWXuyGRsBiZP..9tn0DNJ6Sxddzy",
                            Role = 2,
                            Username = "nguyenvananh123"
                        },
                        new
                        {
                            ID = new Guid("a277d8ae-df9e-4259-909b-a7c790b9389a"),
                            BirthDay = new DateTime(2000, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreate = new DateTime(2022, 6, 14, 10, 0, 14, 0, DateTimeKind.Unspecified),
                            Email = "duonganhhong98@gmail.com",
                            FullName = "DUONG ANH HONG",
                            IsAuthentication = false,
                            IsBLock = false,
                            PasswordHash = "$2a$11$et83i4WKzc1i8ONRvOcfGuigOst/CZEfhJCUChQ8bmga83iW9iELW",
                            Role = 2,
                            Username = "duonganhhong98"
                        },
                        new
                        {
                            ID = new Guid("a177d8ae-df9e-4259-909b-a7c790b9389a"),
                            BirthDay = new DateTime(2000, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreate = new DateTime(2022, 6, 14, 10, 0, 14, 0, DateTimeKind.Unspecified),
                            Email = "lekhanhhoa@gmail.com",
                            FullName = "Le Khanh Hoa",
                            IsAuthentication = false,
                            IsBLock = false,
                            PasswordHash = "$2a$11$w.5QYhJWxHy43hRR8pxX5uqnxUlB/cZ9V..I47u8zEUTAzJuD/A0a",
                            Role = 2,
                            Username = "lekhanhhoa"
                        },
                        new
                        {
                            ID = new Guid("a377d8ae-df9e-4259-909b-a7c790b9389a"),
                            BirthDay = new DateTime(2000, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreate = new DateTime(2022, 6, 14, 10, 0, 14, 0, DateTimeKind.Unspecified),
                            Email = "bao123@gmail.com",
                            FullName = "Pham Tran Huy Bao",
                            IsAuthentication = false,
                            IsBLock = false,
                            PasswordHash = "$2a$11$Ri723fZnkajQ8hiVBvoD2.yA/.PuO35RaWsDlNHO4mfBpBa6WjWNK",
                            Role = 2,
                            Username = "phamtranhuybao123"
                        },
                        new
                        {
                            ID = new Guid("a477d8ae-df9e-4259-909b-a7c790b9389a"),
                            BirthDay = new DateTime(2000, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreate = new DateTime(2022, 6, 14, 10, 0, 14, 0, DateTimeKind.Unspecified),
                            Email = "duyduyduy@gmail.com",
                            FullName = "Van Duy",
                            IsAuthentication = false,
                            IsBLock = false,
                            PasswordHash = "$2a$11$p9wlWXe0bIZlUYJHCreV4uC6Zf754J.BKV06.sXMm5tc0hZ2iGTe.",
                            Role = 2,
                            Username = "duyduyduy1"
                        });
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Answer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            ID = new Guid("ce6882a5-7e2d-4ec0-85c8-c9fc96998da7"),
                            DescriptionAnswer = "tao khong biet",
                            ImageAnswer = "www.image1"
                        },
                        new
                        {
                            ID = new Guid("ec0983cf-316c-4a00-9ea0-9aa5e8a1b44f"),
                            DescriptionAnswer = "dung hoi tao",
                            ImageAnswer = "www.image2"
                        },
                        new
                        {
                            ID = new Guid("6687b5b9-a407-4f34-88af-ef10b58fffc9"),
                            DescriptionAnswer = "tao thua",
                            ImageAnswer = "www.image3"
                        },
                        new
                        {
                            ID = new Guid("8f5be11b-caf1-4a63-9121-0b8b3668fb5d"),
                            DescriptionAnswer = "di hoi thang khac di",
                            ImageAnswer = "www.image4"
                        },
                        new
                        {
                            ID = new Guid("2d9fa7e8-420f-45b9-99e4-031fa241d1b6"),
                            DescriptionAnswer = "de tra google",
                            ImageAnswer = "www.image5"
                        },
                        new
                        {
                            ID = new Guid("35c5e7a7-3176-42fc-8d1b-347809614b90"),
                            DescriptionAnswer = "thoi dep me di",
                            ImageAnswer = "www.image6"
                        },
                        new
                        {
                            ID = new Guid("2f084f72-0692-43ee-8b0f-15644fcef973"),
                            DescriptionAnswer = "chon cau a",
                            ImageAnswer = "www.image6"
                        },
                        new
                        {
                            ID = new Guid("f19beebe-16a5-492e-9197-2ed7ee51effc"),
                            DescriptionAnswer = "chon cau d",
                            ImageAnswer = "www.image6"
                        },
                        new
                        {
                            ID = new Guid("c3b8f3db-e1cb-4af4-b51d-fbe23c826e54"),
                            DescriptionAnswer = "aaaaaaaa",
                            ImageAnswer = "www.image6"
                        },
                        new
                        {
                            ID = new Guid("d10af90d-d41d-4b15-821a-9b928b3b7940"),
                            DescriptionAnswer = "bbbbbbb",
                            ImageAnswer = "www.image6"
                        },
                        new
                        {
                            ID = new Guid("44ef4b9f-217e-4477-9877-98e7fe9bdd6f"),
                            DescriptionAnswer = "ccccccccc",
                            ImageAnswer = "www.image6"
                        });
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Exam", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateExam")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameExam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeExam")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Exam");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b12cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            DateExam = new DateTime(2022, 6, 14, 17, 0, 14, 584, DateTimeKind.Local).AddTicks(6911),
                            NameExam = "De de vai lon",
                            TimeExam = 90
                        },
                        new
                        {
                            ID = new Guid("b22cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            DateExam = new DateTime(2022, 6, 14, 17, 0, 14, 584, DateTimeKind.Local).AddTicks(7304),
                            NameExam = "code 180 phut",
                            TimeExam = 180
                        },
                        new
                        {
                            ID = new Guid("b32cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            DateExam = new DateTime(2022, 6, 14, 17, 0, 14, 584, DateTimeKind.Local).AddTicks(7314),
                            NameExam = "code thoi dung xam lol",
                            TimeExam = 70
                        });
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.ExamQuestion", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Exam.Question");

                    b.HasData(
                        new
                        {
                            ID = new Guid("bff7bee7-66f2-430a-beb0-1bc9179086eb"),
                            ExamID = new Guid("b12cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            TeacherID = new Guid("2c273e26-c2dd-4956-8e13-7c25c2a1158b")
                        },
                        new
                        {
                            ID = new Guid("60123723-badf-4cad-b262-ffd052e28823"),
                            ExamID = new Guid("b12cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b2d"),
                            TeacherID = new Guid("2c273e26-c2dd-4956-8e13-7c25c2a1158b")
                        },
                        new
                        {
                            ID = new Guid("2a9971c2-697d-4821-9d48-6b2ddc8f25d9"),
                            ExamID = new Guid("b12cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b3d"),
                            TeacherID = new Guid("2c273e26-c2dd-4956-8e13-7c25c2a1158b")
                        },
                        new
                        {
                            ID = new Guid("c37c7718-8773-4052-bc91-268000802107"),
                            ExamID = new Guid("b12cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b4d"),
                            TeacherID = new Guid("2c273e26-c2dd-4956-8e13-7c25c2a1158b")
                        },
                        new
                        {
                            ID = new Guid("7c0b8461-85a7-4f70-bf6f-e6a680097bf6"),
                            ExamID = new Guid("b12cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b5d"),
                            TeacherID = new Guid("2c273e26-c2dd-4956-8e13-7c25c2a1158b")
                        },
                        new
                        {
                            ID = new Guid("55cacb3b-8389-4d32-a38e-3da340e445f2"),
                            ExamID = new Guid("b22cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96facc9b6d"),
                            TeacherID = new Guid("2c273e26-c2dd-4956-8e13-7c25c2a1158b")
                        },
                        new
                        {
                            ID = new Guid("807f39e5-4979-436a-9bf4-feef1cb2cc92"),
                            ExamID = new Guid("b22cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b4d"),
                            TeacherID = new Guid("2c273e26-c2dd-4956-8e13-7c25c2a1158b")
                        },
                        new
                        {
                            ID = new Guid("2afd19db-41ba-4905-98e4-9733150d4270"),
                            ExamID = new Guid("b32cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b5d"),
                            TeacherID = new Guid("2c273e26-c2dd-4956-8e13-7c25c2a1158b")
                        });
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.HistoryExam", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateExam")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("AnswerID");

                    b.HasIndex("ExamID");

                    b.HasIndex("QuestionID");

                    b.ToTable("History.Exam");
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Question", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            ImageQuestion = "www.image1 ",
                            NameQuestion = "Con heo co may chan"
                        },
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b2d"),
                            ImageQuestion = "www.image2 ",
                            NameQuestion = "Con cho co may chan"
                        },
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b3d"),
                            ImageQuestion = "www.image3 ",
                            NameQuestion = "Con ga co may chan"
                        },
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b4d"),
                            ImageQuestion = "www.imag4 ",
                            NameQuestion = "Con gan co may chan"
                        },
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b5d"),
                            ImageQuestion = "www.image5 ",
                            NameQuestion = "Con chim co may chan"
                        },
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96facc9b6d"),
                            ImageQuestion = "www.image6 ",
                            NameQuestion = "Con chim mau gi"
                        },
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b6d"),
                            ImageQuestion = "www.image6 ",
                            NameQuestion = "Con gi khong biet boi"
                        },
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b7d"),
                            ImageQuestion = "www.image6 ",
                            NameQuestion = "Ai dep chai nhat"
                        },
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b8d"),
                            ImageQuestion = "www.image6 ",
                            NameQuestion = "Bao cham bao nhieu diem"
                        },
                        new
                        {
                            ID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b9d"),
                            ImageQuestion = "www.image6 ",
                            NameQuestion = "Code tao co sach khong"
                        });
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Table.QuestionAnswer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AnswerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ResultAnswer")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("AnswerID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Question.Answer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnswerID = new Guid("ce6882a5-7e2d-4ec0-85c8-c9fc96998da7"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            ResultAnswer = true
                        },
                        new
                        {
                            ID = 2,
                            AnswerID = new Guid("ec0983cf-316c-4a00-9ea0-9aa5e8a1b44f"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            ResultAnswer = true
                        },
                        new
                        {
                            ID = 3,
                            AnswerID = new Guid("6687b5b9-a407-4f34-88af-ef10b58fffc9"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b2d"),
                            ResultAnswer = false
                        },
                        new
                        {
                            ID = 4,
                            AnswerID = new Guid("8f5be11b-caf1-4a63-9121-0b8b3668fb5d"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b2d"),
                            ResultAnswer = true
                        },
                        new
                        {
                            ID = 5,
                            AnswerID = new Guid("2d9fa7e8-420f-45b9-99e4-031fa241d1b6"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            ResultAnswer = false
                        },
                        new
                        {
                            ID = 6,
                            AnswerID = new Guid("35c5e7a7-3176-42fc-8d1b-347809614b90"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b2d"),
                            ResultAnswer = true
                        },
                        new
                        {
                            ID = 7,
                            AnswerID = new Guid("2f084f72-0692-43ee-8b0f-15644fcef973"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b3d"),
                            ResultAnswer = true
                        },
                        new
                        {
                            ID = 8,
                            AnswerID = new Guid("f19beebe-16a5-492e-9197-2ed7ee51effc"),
                            QuestionID = new Guid("b42cea50-b2e1-4467-91a0-7e96fccc9b2d"),
                            ResultAnswer = false
                        });
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Table.StudentExam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateExam")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid?>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.HasIndex("StudentID");

                    b.ToTable("Student_Exam");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateExam = new DateTime(2022, 6, 14, 10, 0, 14, 587, DateTimeKind.Utc).AddTicks(2087),
                            ExamID = new Guid("b12cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            Score = 7.7999999999999998,
                            Status = true,
                            StudentID = new Guid("9c7b60b6-44b6-4a6f-9c4b-a0ece4672421")
                        },
                        new
                        {
                            ID = 2,
                            DateExam = new DateTime(2022, 6, 14, 10, 0, 14, 587, DateTimeKind.Utc).AddTicks(3756),
                            ExamID = new Guid("b22cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            Score = 9.5,
                            Status = true,
                            StudentID = new Guid("a277d8ae-df9e-4259-909b-a7c790b9389a")
                        },
                        new
                        {
                            ID = 3,
                            DateExam = new DateTime(2022, 6, 14, 10, 0, 14, 587, DateTimeKind.Utc).AddTicks(3767),
                            ExamID = new Guid("b32cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            Score = 4.0,
                            Status = false,
                            StudentID = new Guid("a177d8ae-df9e-4259-909b-a7c790b9389a")
                        },
                        new
                        {
                            ID = 4,
                            DateExam = new DateTime(2022, 6, 14, 10, 0, 14, 587, DateTimeKind.Utc).AddTicks(3773),
                            ExamID = new Guid("b12cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            Score = 8.5,
                            Status = true,
                            StudentID = new Guid("a377d8ae-df9e-4259-909b-a7c790b9389a")
                        },
                        new
                        {
                            ID = 5,
                            DateExam = new DateTime(2022, 6, 14, 10, 0, 14, 587, DateTimeKind.Utc).AddTicks(3779),
                            ExamID = new Guid("b22cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            Score = 6.0,
                            Status = true,
                            StudentID = new Guid("a477d8ae-df9e-4259-909b-a7c790b9389a")
                        },
                        new
                        {
                            ID = 6,
                            DateExam = new DateTime(2022, 6, 14, 10, 0, 14, 587, DateTimeKind.Utc).AddTicks(3792),
                            ExamID = new Guid("b32cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            Score = 6.7000000000000002,
                            Status = true,
                            StudentID = new Guid("a377d8ae-df9e-4259-909b-a7c790b9389a")
                        },
                        new
                        {
                            ID = 7,
                            DateExam = new DateTime(2022, 6, 14, 10, 0, 14, 587, DateTimeKind.Utc).AddTicks(3796),
                            ExamID = new Guid("b22cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            Score = 9.0999999999999996,
                            Status = true,
                            StudentID = new Guid("a177d8ae-df9e-4259-909b-a7c790b9389a")
                        },
                        new
                        {
                            ID = 8,
                            DateExam = new DateTime(2022, 6, 14, 10, 0, 14, 587, DateTimeKind.Utc).AddTicks(3801),
                            ExamID = new Guid("b12cea50-b2e1-4467-91a0-7e96fccc9b1d"),
                            Score = 8.6999999999999993,
                            Status = true,
                            StudentID = new Guid("a277d8ae-df9e-4259-909b-a7c790b9389a")
                        });
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.ExamQuestion", b =>
                {
                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Exam", "Exams")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamID")
                        .HasConstraintName("FK_Exam.Question_Exam  ")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Question", "Questions")
                        .WithMany("QuestionExams")
                        .HasForeignKey("QuestionID")
                        .HasConstraintName("FK_Exam.Question_Question")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Account", "Teacher")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("TeacherID")
                        .HasConstraintName("FK_Exam.Question_Teacher")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Exams");

                    b.Navigation("Questions");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.HistoryExam", b =>
                {
                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Account", "Accounts")
                        .WithMany("HistoryExams")
                        .HasForeignKey("AccountID")
                        .HasConstraintName("FK_History.Exam_Account")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Answer", "Answers")
                        .WithMany("HistoryExams")
                        .HasForeignKey("AnswerID")
                        .HasConstraintName("FK_History.Exam_Answer")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Exam", "Exams")
                        .WithMany("HistoryExams")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Question", "Questions")
                        .WithMany("HistoryExams")
                        .HasForeignKey("QuestionID")
                        .HasConstraintName("FK_History.Exam_Question")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Answers");

                    b.Navigation("Exams");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Table.QuestionAnswer", b =>
                {
                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Answer", "Answers")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("AnswerID")
                        .HasConstraintName("FK_Questions.Answer_Answer  ")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Question", "Questions")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("QuestionID")
                        .HasConstraintName("FK_Questions.Answer_Question")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Answers");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Table.StudentExam", b =>
                {
                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Exam", "Exams")
                        .WithMany("StudentExams")
                        .HasForeignKey("ExamID")
                        .HasConstraintName("FK_Student_Exam_Exam")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ThangDV29_MiniProject_WebAPI.Models.Account", "Students")
                        .WithMany("StudentExams")
                        .HasForeignKey("StudentID")
                        .HasConstraintName("FK_Student_Exam_Student")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exams");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Account", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("HistoryExams");

                    b.Navigation("StudentExams");
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Answer", b =>
                {
                    b.Navigation("HistoryExams");

                    b.Navigation("QuestionAnswers");
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Exam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("HistoryExams");

                    b.Navigation("StudentExams");
                });

            modelBuilder.Entity("ThangDV29_MiniProject_WebAPI.Models.Question", b =>
                {
                    b.Navigation("HistoryExams");

                    b.Navigation("QuestionAnswers");

                    b.Navigation("QuestionExams");
                });
#pragma warning restore 612, 618
        }
    }
}
